### ISSUE TITLE
Vídeo promocional da disciplina

### ISSUE THREAD

**Issue by Dovyski** [fersasil/rupb#1]
Olá, Guilherme!

O seu jogo foi o melhor da disciplina. Ele terá uma aparição maior no vídeo promocional da disciplina. Vou colocar seu nome (e o nome do jogo) na base da tela enquanto as imagens são mostradas.

Gostaria de confirmar se você quer que apareça seu nome ou Fersasil?

**Comment by fersasil** [comment]
Pode ser meu nome
